# CyberSageV2/config/tools.yaml
# --- Tool Selection ---
recon_tools:
  subdomain_discovery: ["subfinder"]
  directory_enumeration: ["dirsearch"]
crawl_tools:
  endpoint_discovery: ["katana"]
scan_tools:
  service_and_version_scanning: ["nmap"]
  ssl_testing: ["testssl"]
  web_server_vuln_scanning: ["nikto"]
service_id_tools:
  technology_identification: ["whatweb"]
vuln_scan_tools:
  template_based_scanning: ["nuclei"]
  xss_specific_scanning: ["dalfox"]
  sqli_specific_scanning: ["sqlmap"]
exploit_tools:
  cve_exploitation: ["searchsploit"]

# --- Tool Paths (CRITICAL: UPDATED BASED ON YOUR 'which' OUTPUT) ---
tool_paths:
  subfinder: "/usr/bin/subfinder" # Using system path found by 'which'
  httpx: "/home/kali/go/bin/httpx " # CRITICAL: Forcing ProjectDiscovery's Go version
  katana: "/home/kali/go/bin/katana"        
  nmap: "/usr/bin/nmap" # Or just "nmap" if /usr/bin is in PATH
  whatweb: "/usr/bin/whatweb" # Or just "whatweb"
  nuclei: "/home/user/go/bin/nuclei"       
  dalfox: "/home/kali/go/bin/dalfox"       
  searchsploit: "/usr/bin/searchsploit" # Or just "searchsploit"
  
  testssl_dir: "/opt/testssl.sh"              
  testssl_script_name: "testssl.sh"           

  nikto_dir: "/opt/nikto" # If /usr/bin/nikto is a wrapper, this might still be needed for plugins
  nikto_script_name: "program/nikto.pl" # Or you can try tool_paths.nikto: "/usr/bin/nikto" if that works

  sqlmap_dir: "/opt/sqlmap" # If /usr/bin/sqlmap is a wrapper, this might be needed for full functionality
  sqlmap_script_name: "sqlmap.py" # Or try tool_paths.sqlmap: "/usr/bin/sqlmap"

  #dirsearch_dir: "/opt/dirsearch"             
  #dirsearch_script_name: "dirsearch.py"       
dirsearch: "/home/kali/.local/bin/dirsearch" 
# --- Wordlists ---
default_wordlist: "~/.cybersage_v2/wordlists/common.txt" 
dirsearch_wordlist: "~/.cybersage_v2/wordlists/common.txt" 

# --- Nuclei Specifics ---
nuclei_update_templates: true 
nuclei_templates_path: "~/.config/nuclei/templates" # More standard path for user-managed templates

# --- AI (OpenRouter) Specifics ---
openai_api_key: "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" 
openrouter_api_base: "https://openrouter.ai/api/v1"
openrouter_model_preference: "mistralai/mistral-7b-instruct" 
openrouter_http_referrer: "http://localhost:5000" 
openrouter_app_title: "CyberSage" 

# --- Tool Specific Options ---
nmap_timing_template: "-T4" 
nmap_default_scripts: true 
nmap_port_scan_options: "--top-ports 1000 -sT -n --min-rate 1000 --max-retries 1" 

katana_crawl_depth: 1 
katana_concurrency: 10 # Katana uses -c flag
dalfox_timeout: 120   
dalfox_workers: 10    # Dalfox v2 uses -w <number> flag. Verify with `dalfox --help`.
testssl_timeout: 180
dirsearch_threads: 15
dirsearch_max_time: 120 
dirsearch_extensions: "php,html,htm,js,txt,json,xml,bak,config,md,sql,env,yml,yaml"
dirsearch_exclude_status: "400,403,404,500-599,429"
sqlmap_level: 1 
sqlmap_risk: 1  
sqlmap_options: "--batch --random-agent --threads=3 --smart --forms --crawl=0" 
nikto_options: "-Tuning x 0123bde -maxtime 120s -nointeractive"
